site_name: Dokumentacja NASweb
icon: favicon.png
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: pl
  logo: image.png
  palette:
    primary: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Start: 
    - index.md
  - Informacje techniczne:
    - Home.md
    - NASweb-polski.md
    - NASweb-english.md
  - Aplikacja:
    - Aplikacja/index.md
    - Aplikacja/Aplikacja.md
    - Panel: 
      - Aplikacja/Panel/Pulpit.md
      - Aplikacja/Panel/Urządzenie.md
      - Aplikacja/Panel/Monitor-zdarzeń.md

      - Kontrola dostępu:
        - Aplikacja/Panel/Użytkownicy.md
        - Aplikacja/Panel/Karty.md
        - Aplikacja/Panel/Wzorce-uprawnień.md
        - Aplikacja/Panel/Przejścia-i-Czytniki.md

      - SSWiN:
        - Aplikacja/Panel/Strefy.md
        - Aplikacja/Panel/Wejścia.md
        - Aplikacja/Panel/Wyjścia-(strefy).md

      - Aplikacja/Panel/Wideorejestracja.md
      - Aplikacja/Panel/Status.md

      - Ustawienia:
        - Ustawienia/Pulpit.md
        - Ustawienia/GSM.md
        - Ustawienia/Wejścia.md
        - Ustawienia/CMS.md
        - Ustawienia/Email.md
        - Ustawienia/Konfiguracja-formatu-kart.md
        - Ustawienia/Kamery.md
        - Ustawienia/Campics.md
        - Ustawienia/Powiadomienia.md
        - Ustawienia/Linki-zewnętrzne.md
        
      - Skrypty:
        - Aplikacja/Panel/Pliki-skryptów.md
        - Aplikacja/Panel/Filtry-skryptów.md
        - Aplikacja/Panel/Logi-skryptów.md

      - Aplikacja/Panel/Admin.md
  - Kontroler:
    - Kontroler/index.md
  - Home Assistant:
    - HomeAssistant/Home-Assistant-Operating-System.md
    - HomeAssistant/Instalacja-integracji.md
  - Dodatki:
    - Dodatki/index.md
  - FAQ:
    - FAQ/index.md